# Generated by Django 6.0.6 on 2026-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('banner_image_url', models.URLField(blank=True, help_text='Alternative URL for course banner image', null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor_name', models.CharField(max_length=150)),
                ('duration', models.CharField(help_text='e.g. 6 Weeks', max_length=100)),
                ('course_overview', models.TextField(blank=True, help_text='Detailed overview of the course content')),
                ('last_remarks', models.TextField(blank=True, help_text='Final remarks or review comments')),
                ('category', models.CharField(default='LEADERSHIP AND PERSONAL DEVELOPMENT', max_length=150)),
                ('level', models.CharField(default='Advanced', max_length=100)),
                ('modules_count', models.IntegerField(default=6)),
                ('students_count', models.IntegerField(default=5)),
            ],
        ),
    ]
